House/urls.py
from django.urls import path
from .views import home,login,SubmitRent,SubmitSell,about,contact,blog,Reqbuy,Reqrent,myfile,reqrents,reqbuys,submitrents,submitsells,sell_detail,rent_detail,req_rent_detail,req_buy_detail
from django.contrib.auth import views as auth_views

app_name = 'bayatamlak'
urlpatterns = [
    path('',home,name = 'home'),
    path('login/',login,name='login'),
    path('submitsell/',SubmitSell,name='submitsell'),
    path('about/',about,name='about'),
    path('contact/',contact,name='contact'),
    path('blog/',blog,name='blog'),
    path('reqrent/',Reqrent,name='reqrent'),
    path('reqbuy/',Reqbuy,name='reqbuy'),
    path('submitrent/',SubmitRent,name='submitrent'),
    path('reqrents/',reqrents,name='reqrents'),
    path('reqbuys/',reqbuys,name='reqbuys'),
    path('submitrents/',submitrents,name='submitrents'),
    path('submitsells/',submitsells,name='submitsells'),
    # path('myfile/',myfile,name='myfile')
    path('myfiles/',myfile,name='myfiles'),
    path('sell_detail/<int:id>/',sell_detail,name='sell_detail'),
    path('rent_detail/<int:id>/',rent_detail,name='rent_detail'),
    path('req_rent_detail/<int:id>/',req_rent_detail,name='req_rent_detail'),
    path('req_buy_detail/<int:id>/',req_buy_detail,name='req_buy_detail')
]

amlak/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bayatamlak/',include('House.urls'))
]

House/forms.py
from re import L
from django.db import models
from django.forms import widgets
from django.forms.widgets import RadioSelect
from .models import  rental,selling ,reqmostager,reqkharid, rhouse,shouse,mani,User
from django.forms import ModelForm , Textarea
from django import forms

class rent(ModelForm):
    
    class Meta:
        model = rental
        exclude =['moshaver']
class mani(ModelForm):
    
    class Meta:
        model = mani
        exclude =['moshaver']
        labels ={ 'datei':'datei','mani':'mani'}

class sell(ModelForm):
    
    class Meta:
        model = selling
        exclude =['moshaver']
        labels ={'title':'title','SellerName':'SellerName','SellerFamily':'SellerFamily',
                'SellerPhone':'SellerPhone','moshaver':'moshaver','price':'price',
                'size':'size','room':'room','phase':'phase','Floor':'Floor','Address':'Address',
                    'elsei':'elsei','facility':'facility'}

class reqrent(ModelForm):
    
    class Meta:
        model = reqmostager
        exclude =['moshaver']
        labels ={'title':'title','Name':'Name','Phone':'Phone',
                'rahn':'rahn','ejare':'ejare','phase':'phase',
                'elsei2':'elsei2','room':'room','elsei':'elsei',}

class reqbuy(ModelForm):
    
    class Meta:
        model = reqkharid
        exclude =['moshaver']
        labels ={'title':'title','Name':'Name','Phone':'Phone',
                'mojodi':'mojodi','elsei':'elsei',
                'room':'room','phase':'phase','elsei2':'elsei2'}
        

class renthouse(ModelForm):
    class Meta:
        model = rhouse
        exclude =['moshaver']
        labels ={'title':'title','Name':'Name',
                'Phone':'Phone','rahn':'rahn','ejare':'ejare',
                'size':'size','room':'room','phase':'phase','Floor':'Floor','Address':'Address',
                    'elsei':'elsei','elsei2':'elsei2'}

class sellhouse (ModelForm):
    
    class Meta:
        model = shouse
        exclude =['moshaver']
        labels ={'title':'title','Name':'Name',
                'Phone':'Phone','price':'price',
                'size':'size','room':'room','phase':'phase','Floor':'Floor','Address':'Address',
                    'elsei':'elsei','elsei2':'elsei2'}

class userlogin (forms.Form):
    email = forms.EmailField(label='email')
    phone = forms.CharField(label='phone')
    password = forms.CharField(widget=forms.PasswordInput(), label='password')
    

House/views.py
from audioop import reverse
from multiprocessing import context
from django.shortcuts import render ,redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate , login
from .models import selling , shouse,rhouse,reqkharid,reqmostager
from .forms import   renthouse,sellhouse,reqbuy,reqrent,mani,userlogin
from django.contrib.auth.decorators import login_required
import datetime
from itertools import chain
from operator import attrgetter

now = datetime.datetime.now().date()
current_datetime = datetime.datetime.now().hour
# Create your views here.
date_1 = datetime.datetime.strptime(str(now), "%Y-%m-%d")
end_date = date_1 + datetime.timedelta(days=1)
end_date = end_date.date()
def home(request): 
    form = userlogin(request.POST)
    if request.method == 'POST':
        print('suck')
        form = userlogin(request.POST)
        if form.is_valid():
            print('fuck')
            cd = form.cleaned_data
            useri = authenticate(request ,email = cd['email'],phone=cd['phone'],password = cd['password'])
            print('fuck you ')
            if useri is not None:
                print('nock nock')
                login(request,useri)
                return redirect('bayatamlak:myfiles')
        
    else :
        form = userlogin()
    return render(request,'login.html',{'form':form})
    # context = {
    #     'selling':selling.objects.all(),
    #     'rent':rent(),
    #     'mog':mog(),
    #     'mos':mos(),
    #     'senti':senti()
    # }    
    # form = mani()
    # if request.method == 'POST':
    #     form = mani(request.POST)
    #     if form.is_valid():
    #         res = form.save(commit=False)
    #         res.moshaver = request.user
    #         res.save()        
    #         return render(request,'reqbuy.html',{'reqbuy':mani})
            
    # return render(request,'home.html',{'reqbuy':mani}) 
# def loglog(request):
    # form = userlogin(request.POST)
    # if request.method == 'POST':
    #     print('suck')
    #     form = userlogin(request.POST)
    #     if form.is_valid():
    #         print('fuck')
    #         cd = form.cleaned_data
    #         useri = authenticate(request ,email = cd['email'],phone=cd['phone'],password = cd['password'])
    #         print('fuck you ')
    #         if useri is not None:
    #             print('nock nock')
    #             login(request,useri)
    #             return redirect('bayatamlak:reqbuy')
        
    # else :
    #     form = userlogin()
        
    # return render(request,'login.html',{'form':form})
def post(request):
    context = {
        'selling':selling.objects.all()
    }
    return render(request,'index.html',context)
@login_required(login_url='/bayatamlak/')
def SubmitRent(request):
    form = renthouse()
    if request.method == 'POST':
        form = renthouse(request.POST)
        if form.is_valid():            
            res = form.save(commit=False)
            res.moshaver = request.user
            res.save()
            return redirect('bayatamlak:myfiles')
    return render(request,'submit_rent.html',{'form':form})
@login_required(login_url='/bayatamlak/')
def Reqbuy(request):
    form = reqbuy()
    if request.method == 'POST':
        form = reqbuy(request.POST, request.FILES )
        if form.is_valid():
            res = form.save(commit=False)
            res.moshaver = request.user
            res.save()
            return redirect('bayatamlak:myfiles')
    return render(request,'reqbuy.html',{'reqbuy':reqbuy})
@login_required(login_url='/bayatamlak/')
def Reqrent(request):
    form = reqrent()
    if request.method == 'POST':
        form = reqrent(request.POST)
        if form.is_valid():
            res = form.save(commit=False)
            res.moshaver = request.user
            res.save()
            return redirect('bayatamlak:myfiles')
            
            
        
    return render(request,'reqrent.html',{'reqrent':reqrent})

@login_required(login_url='/bayatamlak/')    
def SubmitSell(request):
    form = sellhouse()
    if request.method == 'POST':
        form = sellhouse(request.POST)
        if form.is_valid():
            res = form.save(commit=False)
            res.moshaver = request.user
            res.save()
            return redirect('bayatamlak:myfiles')
    return render(request,'submit_sell.html',{'sellhouse':sellhouse})
def about(request):
    context = {
        'selling':selling.objects.all()
    }
    return render(request,'about.html',context)
def contact(request):
    form = reqbuy()
    if request.method == 'POST':
        form = reqbuy(request.POST, request.FILES )
        if form.is_valid():
            res = form.save(commit=False)
            res.moshaver = request.user
            res.save()
    return render(request,'contact.html',{'reqbuy':reqbuy})
def blog(request):
    form = mani()
    if request.method == 'POST':
        form = mani(request.POST)
        if form.is_valid():
            res = form.save(commit=False)
            res.moshaver = request.user
            res.save()
    return render(request,'property_single.html',{'form':mani})

@login_required(login_url='/bayatamlak/')    
def myfile(request):
    sellhouses = shouse.objects.filter(moshaver=request.user)
    renthouses = rhouse.objects.filter(moshaver=request.user)
    reqrental = reqmostager.objects.filter(moshaver=request.user)
    reqbuuy = reqkharid.objects.filter(moshaver=request.user)
    result_list = sorted(list(chain(sellhouses,renthouses,reqrental,reqbuuy)),key=attrgetter('data_created'),reverse=True)
    context = {'result_list':result_list
    }
    return render(request,'myfiles.html',context)
@login_required(login_url='/bayatamlak/')
def reqrents(request):
    context = {'result_list':reqmostager.objects.all().order_by('-data_created')}
    return render(request,'reqrents.html',context)
@login_required(login_url='/bayatamlak/')
def reqbuys(request):
    context = {'result_list':reqkharid.objects.all().order_by('-data_created')}
    return render(request,'reqbuys.html',context)
@login_required(login_url='/bayatamlak/')
def submitrents(request):
    context = {'result_list':rhouse.objects.all().order_by('-data_created')}
    return render(request,'submit_rents.html',context)
@login_required(login_url='/bayatamlak/')
def submitsells(request):
    context = {'result_list':shouse.objects.all().order_by('-data_created')}
    return render(request,'submit_sells.html',context)

@login_required(login_url='/bayatamlak/')    
def sell_detail(request,id):
    sellhouse = shouse.objects.get(id=id)
    
    context = {'form':sellhouse
    }
    return render(request,'sell_detail.html',context)
@login_required(login_url='/bayatamlak/')    
def rent_detail(request,id):
    renthouses = rhouse.objects.get(id=id)
    context = {'form':renthouses
    }
    return render(request,'rent_detail.html',context)

@login_required(login_url='/bayatamlak/')    
def req_buy_detail(request,id):
    reqbuuy = reqkharid.objects.get(id=id)
    context = {'form':reqbuuy
    }
    return render(request,'req_sell_detail.html',context)

@login_required(login_url='/bayatamlak/')    
def req_rent_detail(request,id):
    reqrental = reqmostager.objects.get(id=id)
    context = {'form':reqrental
    }
    return render(request,'req_rent_detail.html',context)

House/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
<link href="{% static 'assets/css/all.css' %}" rel="stylesheet">
<!-- Owl Carousel CSS -->
<link href="{% static 'assets/css/owl.carousel.css' %}" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
<link href="{% static 'assets/css/animate.css' %}" rel="stylesheet">
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
<title>Real Estate</title>
</head>
<body>


<!--Header Start-->
<div class="header-wrap wow fadeInUp">
  <div class="container">
    <div class="row">
      <div class="col-lg-3 navbar navbar-expand-lg navbar-light">
        <!-- <div class="header_logo"><a href="#"><img src="{% static 'assets/images/logo.png' %}"></a></div> -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
      </div>
      <div class="col-lg-9">
        <nav class="navbar navbar-expand-lg navbar-light"> <a class="navbar-brand" href="#">Navbar</a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <button class="close-toggler" type="button" data-toggle="offcanvas"> <span><i class="fas fa-times-circle" aria-hidden="true"></i></span> </button>
            <ul class="navbar-nav mr-auto">
              <!-- <li class="nav-item"><a class="nav-link" href="{% url 'bayatamlak:home' %}">ورود/a></li> -->
              <!-- <li class="nav-item"><a class="nav-link" href="{% url 'bayatamlak:home' %}"> خانه</a></li> -->
              <li class="nav-item active"><a class="nav-link" href="index.html"> ثبت <span class="caret"><i class="fas fa-caret-down"></i></span></a> <i class="fas fa-caret-down"></i>
                <ul class="submenu">
                  <li><a href="{% url 'bayatamlak:reqbuy' %}"> ثبت درخواست خرید</a></li>
                  <li><a href="{% url 'bayatamlak:reqrent' %}"> ثبت درخواست اجاره </a></li>
                  <li><a href="{% url 'bayatamlak:submitsell' %}">ثبت  فایل فروش</a></li>
                  <li><a href="{% url 'bayatamlak:submitrent' %}"> ثبت فایل اجاره</a></li>
                </ul>
              </li>
              <li class="nav-item"><a class="nav-link" href="{% url 'bayatamlak:home' %}">ورود</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'bayatamlak:myfiles' %}">فایل های من</a></li>
                
              
              <li class="nav-item"><a class="nav-link" href="{% url 'bayatamlak:reqbuys' %}">درخواست های خرید</a></li>
                
              
              <li class="nav-item"><a class="nav-link" href="{% url 'bayatamlak:reqrents' %}">درخواست های اجاره</a></li>
                
              
              <li class="nav-item"><a class="nav-link" href="{% url 'bayatamlak:submitsells' %}"> فایل های فروشی </a></li>
                
              
              <li class="nav-item"><a class="nav-link" href="{% url 'bayatamlak:submitrents' %}">فایل های اجاره</a></li>
            </ul>
          </div>
        </nav>
      </div>
    </div>
  </div>
</div>
<!--Header End--> 
        {% block base %}
        {% endblock %}
        <!--Footer Start-->
<footer class="footer bg-style wow fadeInUp">
    <div class="container">
      <div class="footer-upper">
        <div class="row">
          <div class="col-lg-3 col-md-12">
            <div class="footer-widget about-widget"> <a href="#"> <img src="{% static 'assets/images/logo2.png' %}" alt="Awesome Image"> </a>
              
              
            </div>
          </div>
          <div class="col-lg-2 col-md-3">
            <div class="footer-widget quick-links">
              <h3 class="title">لینک های سریع</h3>
              <ul>
                <!-- <li><a href="#."> خانه</a> </li>
                <li><a href="#."> خصوصیات</a> </li>
                <li><a href="#."> مشاوران</a> </li>
                <li><a href="#."> وبلاگ</a> </li>
                <li><a href="#."> تماس با ما</a> </li> -->
              </ul>
            </div>
          </div>
          <div class="col-lg-4 col-md-5">
            <div class="footer-widget contact">
              <h3 class="title">ویژگی های اخیر</h3>
              <ul class="property_sec">
                <li>
                  <div class="rec_proprty">
                    <div class="propertyImg"><img src="{% static 'assets/images/property_small01.jpg' %}"></div>
                    <div class="property_info">
                      <h4><a href="#">پرند میدان استقلال </a></h4>
                      
                      
                    </div>
                  </div>
                </li>
                <li>
                  <div class="rec_proprty">
                    <div class="propertyImg"><img src="{% static 'assets/images/property_small02.jpg' %}"></div>
                    <div class="property_info">
                      <h4><a href="#">پرند میدان استقلال </a></h4>
                      
                      
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-4">
            <div class="footer-widget contact">
              <h3 class="title">اطلاعات تماس</h3>
              <ul class="footer-adress">
                <li class="footer_address"> <i class="fas fa-map-signs"></i> <span>پرند میدان استقلال </span> </li>
                <li class="footer_email"> <i class="fas fa-envelope" aria-hidden="true"></i> <span><a href="mailto:info@realestate.com"> info@realestate.com </a></span> </li>
                <li class="footer_phone"> <i class="fas fa-phone-alt"></i> <span><a href="tel:02157459"> 57459</a></span> </li>
              </ul>
              <div class="social-icons footer_icon">
                <ul>
                  <li><a href="#"><i class="fab fa-facebook-f" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
                  <li><a href="#"><i class="fab fa-youtube" aria-hidden="true"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!--Footer End--> 
<!-- Optional JavaScript --> 
<!-- jQuery first, then Popper.js, then Bootstrap JS --> 
<script src="{% static 'assets/js/jquery.min.js' %}"></script> 
<script src="{% static 'assets/js/popper.min.js' %}"></script> 
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script> 
<!-- Owl Carousel --> 
<script src="{% static 'assets/js/owl.carousel.js' %}"></script> 
<!-- wow js --> 
<script src="{% static 'assets/js/animate.js' %}"></script> 
<script>
  new WOW().init();
</script> 
<!-- general script file --> 
<script src="{% static 'assets/js/wow.js' %}"></script> 
<script src="{% static 'assets/js/script.js' %}"></script>
</body>
</html>

House/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block base %}
<form action="" method="post">
  {% csrf_token %}
  {{form}}
  <input type="submit" value="login">
</form>
{% endblock %}

House/templates/myfiles.html
{% extends 'base.html' %}
{% load static %}
{% block base %}
<!--Inner Heading Start-->
<div class="innerHeading">
  <div class="container">
    <h1>فایل های من</h1>
  </div>
</div>
<!--Inner Heading End--> 

<!--Inner Content Start-->
<div class="innercontent">
  <div class="container">
    <div class="row listing_wrap">
      <div class="col-lg-4">
        
        
        
      </div>
      <div class="col-lg-8">
        
        
        <!--Row Start-->
        
        <ul class="row">
          {% for result in result_list %}
          <!--col-lg-4 Start-->
          <li class="col-lg-6">
            <div class="property_box wow fadeInUp">
              {% if result.position == 'اجاره' %}
              <h3><a href="{% url 'bayatamlak:rent_detail' result.id %}">{{result.title}}</a></h3>
              {% elif result.position == 'فروشی' %}
              <h3><a href="{% url 'bayatamlak:sell_detail' result.id %}">{{result.title}}</a></h3>
              {% elif result.position == 'درخواست خرید' %}
              <h3><a href="{% url 'bayatamlak:req_buy_detail' result.id %}">{{result.title}}</a></h3>
              {% elif result.position == 'درخواست اجاره' %}
              <h3><a href="{% url 'bayatamlak:req_rent_detail' result.id %}">{{result.title}}</a></h3>
              {% endif %}
              {% if result.rahn  %}
              <div class="property_price">{{result.rahn}}  تومان رهن</div>
              <div class="heart_info">
                <div class="heart_icon"><a href="#"><i class="fas fa-heart"></i></a></div>
                <!-- <div class="heart_icon exchange_icon"><a href="#"><i class="fas fa-exchange-alt"></i></a></div> -->
                <div class="property_price"> {{result.ejare}}  تومان اجاره </div> 
              </div>
              {% elif result.price %}
              <div class="property_price">{{result.price}}  تومان </div>
              <div class="heart_info">
                <div class="heart_icon"><a href="#"><i class="fas fa-heart"></i></a></div>
                <!-- <div class="heart_icon exchange_icon"><a href="#"><i class="fas fa-exchange-alt"></i></a></div> -->
                <div class="property_price"> {{result.ejare}}    </div> 
              </div>
              {% elif result.mojodi %}
              <div class="property_price">{{result.mojodi}}  تومان </div>
              <div class="heart_info">
                <div class="heart_icon"><a href="#"><i class="fas fa-heart"></i></a></div>
                <!-- <div class="heart_icon exchange_icon"><a href="#"><i class="fas fa-exchange-alt"></i></a></div> -->
                <div class="property_price"> {{result.ejare}}    </div> 
              </div>
              {% endif %}
              <div class="propert_info">
                <ul class="row">
                  <li class="col-4">
                    
                    <h5>اتاق خواب {{result.room}}</h5>
                  </li>
                  <li class="col-4">
                    
                    <h5> فاز {{result.phase}}</h5>
                  </li>
                  <li class="col-4">
                    
                    <h5> پروژه {{ result.elsei2}}</h5>
                  </li>
                </ul>
              </div>
              <div class="rent_info">
                <div class="apart"><a href="tel:{{ result.Phone }}">{{ result.Name }}</a></div>
                <div class="sale">{{result.position}}</div>
              </div>
            </div>
          </li>
          <!--col-lg-4 End--> 
          {% endfor %}
          <!--col-lg-4 Start-->
          
          
        </ul>
        <!--Row End-->
        
        <!-- <div class="blog-pagination text-center"> <a href="#0"><i class="fas fa-angle-right"></i></a> <a href="#0">1</a> <a href="#0" class="active">2</a> <a href="#0">3</a> <a href="#0"><i class="fas fa-angle-left"></i></a> </div> -->
      </div>
    </div>
  </div>
</div>

<!--Inner Content End--> 
{% endblock %}

House/templates/reqrents.html
{% extends 'base.html' %}
{% load static %}
{% block base %}
<div class="innerHeading">
  <div class="container">
    <h1>درخواست های اجاره</h1>
  </div>
</div>
<!--Inner Heading End--> 

<!--Inner Content Start-->
<div class="innercontent">
  <div class="container">
    <div class="row listing_wrap">
      <div class="col-lg-4">
        
        
       
      </div>
      <div class="col-lg-8">
        
        
        <!--Row Start-->
        
        <ul class="row">
          {% for result in result_list %}
          <!--col-lg-4 Start-->
          <li class="col-lg-6">
            <div class="property_box wow fadeInUp">
              
              <h3><a href="{% url 'bayatamlak:req_rent_detail' result.id %}">{{result.title}}</a></h3>
              {% if result.rahn  %}
              <div class="property_price">{{result.rahn}}  تومان رهن</div>
              <div class="heart_info">
                <div class="heart_icon"><a href="#"><i class="fas fa-heart"></i></a></div>
                <!-- <div class="heart_icon exchange_icon"><a href="#"><i class="fas fa-exchange-alt"></i></a></div> -->
                <div class="property_price"> {{result.ejare}}  تومان اجاره </div> 
              </div>
              {% elif result.price %}
              <div class="property_price">{{result.price}}  تومان </div>
              <div class="heart_info">
                <div class="heart_icon"><a href="#"><i class="fas fa-heart"></i></a></div>
                <!-- <div class="heart_icon exchange_icon"><a href="#"><i class="fas fa-exchange-alt"></i></a></div> -->
                <div class="property_price"> {{result.ejare}}    </div> 
              </div>
              {% elif result.mojodi %}
              <div class="property_price">{{result.mojodi}}  تومان </div>
              <div class="heart_info">
                <div class="heart_icon"><a href="#"><i class="fas fa-heart"></i></a></div>
                <!-- <div class="heart_icon exchange_icon"><a href="#"><i class="fas fa-exchange-alt"></i></a></div> -->
                <div class="property_price"> {{result.ejare}}    </div> 
              </div>
              {% endif %}
              <div class="propert_info">
                <ul class="row">
                  <li class="col-4">
                    
                    <h5>اتاق خواب {{result.room}}</h5>
                  </li>
                  <li class="col-4">
                    
                    <h5> فاز {{result.phase}}</h5>
                  </li>
                  <li class="col-4">
                    
                    <h5> پروژه {{ result.elsei2}}</h5>
                  </li>
                </ul>
              </div>
              <div class="rent_info">
                <div class="apart"><a href="tel:{{ result.moshaver.phone }}">{{ result.moshaver.name }}</a></div>
                <div class="sale">{{result.position}}</div>
              </div>
            </div>
          </li>
          <!--col-lg-4 End--> 
          {% endfor %}
          <!--col-lg-4 Start-->
          
          
        </ul>
        <!--Row End-->
        
        
      </div>
    </div>
  </div>
</div>


<!--Inner Content End--> 
{% endblock %}

House/templates/submit_sells.html
{% extends 'base.html' %}
{% load static %}
{% block base %}
<div class="innerHeading">
  <div class="container">
    <h1>درخواست های اجاره</h1>
  </div>
</div>
<!--Inner Heading End--> 

<!--Inner Content Start-->
<div class="innercontent">
  <div class="container">
    <div class="row listing_wrap">
      <div class="col-lg-4">
        
        
       
      </div>
      <div class="col-lg-8">
        
        
        <!--Row Start-->
        
        <ul class="row">
          {% for result in result_list %}
          <!--col-lg-4 Start-->
          <li class="col-lg-6">
            <div class="property_box wow fadeInUp">
              
              <h3><a href="{% url 'bayatamlak:sell_detail' result.id %}">{{result.title}}</a></h3>
              {% if result.rahn  %}
              <div class="property_price">{{result.rahn}}  تومان رهن</div>
              <div class="heart_info">
                <div class="heart_icon"><a href="#"><i class="fas fa-heart"></i></a></div>
                <!-- <div class="heart_icon exchange_icon"><a href="#"><i class="fas fa-exchange-alt"></i></a></div> -->
                <div class="property_price"> {{result.ejare}}  تومان اجاره </div> 
              </div>
              {% elif result.price %}
              <div class="property_price">{{result.price}}  تومان </div>
              <div class="heart_info">
                <div class="heart_icon"><a href="#"><i class="fas fa-heart"></i></a></div>
                <!-- <div class="heart_icon exchange_icon"><a href="#"><i class="fas fa-exchange-alt"></i></a></div> -->
                <div class="property_price"> {{result.ejare}}    </div> 
              </div>
              {% elif result.mojodi %}
              <div class="property_price">{{result.mojodi}}  تومان </div>
              <div class="heart_info">
                <div class="heart_icon"><a href="#"><i class="fas fa-heart"></i></a></div>
                <!-- <div class="heart_icon exchange_icon"><a href="#"><i class="fas fa-exchange-alt"></i></a></div> -->
                <div class="property_price"> {{result.ejare}}    </div> 
              </div>
              {% endif %}
              <div class="propert_info">
                <ul class="row">
                  <li class="col-4">
                    
                    <h5>اتاق خواب {{result.room}}</h5>
                  </li>
                  <li class="col-4">
                    
                    <h5> فاز {{result.phase}}</h5>
                  </li>
                  <li class="col-4">
                    
                    <h5> پروژه {{ result.elsei2}}</h5>
                  </li>
                </ul>
              </div>
              <div class="rent_info">
                <div class="apart"><a href="tel:{{ result.moshaver.phone }}">{{ result.moshaver.name }}</a></div>
                <div class="sale">{{result.position}}</div>
              </div>
            </div>
          </li>
          <!--col-lg-4 End--> 
          {% endfor %}
          <!--col-lg-4 Start-->
          
          
        </ul>
        <!--Row End-->
        
        
      </div>
    </div>
  </div>
</div>
<!--Inner Content End--> 
{% endblock %}